In [12]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

from Lib_trust_region import mRC_SR1
from Lib_kmeans_softmin import crear_objetivo_kmeans_softmin, asignaciones_duras

In [13]:
#Importa los datos sobre los cuales se van a trabajar 
#Para este ejemplo se va a usar 
ruta = "iris/iris.data"

columnas = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
df = pd.read_csv(ruta, header=None, names=columnas) 

#Estandarizamos los datos (que esten en la misma escala)
X = df.iloc[:, :-1].values 


scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [14]:
# 4. Configuración de Soft K-Means
k = 3          # Sabemos que Iris tiene 3 especies (Setosa, Versicolor, Virginica)
d = X.shape[1] # 4 características por flor
tau = 0.5      # Parámetro de suavizado (temperatura)

#print(d)
f_objetivo = crear_objetivo_kmeans_softmin(X_scaled, k, tau, promedio=True)
  

4


In [20]:
np.random.seed(42)
W0 = np.random.randn(k, d) # Inicializamos aleatoriamente
w0_flat = W0.flatten()

w_opt_flat = mRC_SR1(f=f_objetivo, x0=w0_flat, maxDelta=10.0, imax=200, tol=1e-4, delta=1.0, dogLeg=True)


# Reconstruimos los centroides 
W_opt = w_opt_flat.reshape((k, d)) 

print("Los centros son: ")
print(W_opt)
print("El valor mínimo es: ")
print(f_objetivo(W_opt))
labels_pred = asignaciones_duras(X_scaled, W_opt)
print(labels_pred)

#print(len(labels_pred))

Happy iteration in 15
Los centros son: 
[[-0.02552019 -0.86419196  0.3492485   0.28066009]
 [ 1.03950449  0.02338899  0.95163279  0.97204103]
 [-1.01143056  0.85112976 -1.30299056 -1.25394157]]
El valor mínimo es: 
0.9675835736009917
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0
 0 1 1 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1
 1 1 0 0 1 1 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1 1 1 0 1
 1 0]
